apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        # image: 'gcr.io/codeeducation-test-278602/app-laravel:415189b'
        image: img-app-deployment
        ports:
        - containerPort: 80

        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password

        envFrom:
        - configMapRef:
            name: app-conf

        volumeMounts:
        - name: app-conf
          mountPath: /var/www/.env
          subPath: .env

      volumes:
      - name: app-conf
        configMap:
          name: app-conf
          items:
            - key: env
              path: .env
